Korean changes
GreyWyvern/virtual-keyboard pull request #5
Opened 2024-08-28 16:32 UTC by VitaJane

Here are the changes for making the Korean Layout work.
  - Updated Unicode for Jamo characters used in the Korean layout to the current versions
  - Add algorithms and what not to handle Jamo input to get Hangul 
  - Added complete button to allow users to start a new Hangul character without it combining to the previous
 
Note: Hangul is the Korean writing system and Jamo are the individual characters that make up Hangul.

2024-08-28 17:14 UTC, GreyWyvern commented
Okay, so first of all, this is great. I don't know how a Korean keyboard with these hangul-combining key sequences actually works, but your additions seem to work fine and without errors. It's apparent a great deal of work has gone into this, so great job!

Apart from some code styling and convention issues, the major concern I have is that a large part of the code (between the 'For Korean input' and 'End for Korean input') occurs outside the `(function() { ... })();` scope which means it's global for any other script on the page to conflict with. All of these variables and functions need to be moved inside the function scope and ideally have their names updated to reduce the risk of conflicts. I suggest a prefix of `VKI_KO_` for the Korean-related functions and variables.

As well, I realize that some of the additions cannot be moved since they add to the existing logic, however if the majority of added code could be grouped into one location, then users could easily remove it if they decide not to use the Korean keyboard and save on script size.

A few other things confuse me a bit, like how you have a function `kEvent()` that clears the `current` array and the Complete button content, but the function seems to be duplicated by the `clearCurrent()` function, and in several other places the `current` variable and Complete button are cleared manually, but neither of these functions is called.

Those things can wait until after the KO functions are moved into the keyboard function scope. Let me know if you'd like me to do that for you.

Thanks again for this PR!

2024-08-28 19:17 UTC, VitaJane commented
I can go ahead and make those changes.

2024-08-29 15:44 UTC, VitaJane commented
Alright, I made those changes you suggested. You were right, there were some things that were basically just doing the same thing so I fixed those.

2024-08-29 16:03 UTC, GreyWyvern commented
Looks great! Everything else apart from code-style issues (I can tinker with those later) seems fine, however I did find a bug.

If I type in two or three Korean jamo that combine and do NOT press the Combine key, then I switch to another keyboard, then press the Backspace key, there is a javascript error.

Switching to another keyboard layout should probably complete the Korean character and reset the Complete button.

2024-08-29 19:07 UTC, VitaJane commented
I went ahead and fixed the bug.

2024-08-29 19:21 UTC, GreyWyvern commented
It seems fixed now, thanks! Just the `currentStyle` revert and I think it is ready to merge.

Any other edits you'd like to make here? Would you like to add your name and / or contact info in the file header? You can add it before the Github link, and make it something like: "Korean Jamo to Hangul input by ..."

This is a great addition to the script. I really appreciate it!

2024-08-29 19:42 UTC, VitaJane commented
Yeah, I actually have a few more big changes I made. Made a tweak to the language dropdown so you could see the English names next to the native name (optionally) and made it searchable. Also added a help button and made the keyboard movable it's self. Don't know if you want these changes. And yeah, I'd love to add my name to the header.

2024-08-29 19:48 UTC, GreyWyvern commented
> Yeah, I actually have a few more big changes I made. Made a tweak to the language dropdown so you could see the English names next to the native name (optionally) and made it searchable. Also added a help button and made the keyboard movable it's self. Don't know if you want these changes.

I meant related to this PR. I'd definitely like to see your other changes in separate PRs.

> And yeah, I'd love to add my name to the header.

Please do!

2024-08-29 20:15 UTC, VitaJane commented
Sorry my bad, misunderstood. I went added to the header, that should be everything for the PR.

2024-08-29 20:16 UTC, GreyWyvern requested changes

2024-08-29 20:16 UTC, GreyWyvern commented on keyboard.js
> +      y = obj.VKI_KO_currentStyle[styleProp];
One more change. This should remain just `currentStyle`.

2024-08-29 20:18 UTC, VitaJane commented
Just fixed it

2024-08-29 20:19 UTC, GreyWyvern approved these changes

2024-08-29 20:22 UTC, merged

2024-08-29 20:24 UTC, GreyWyvern commented
Thanks very much for all your hard work!