Movement
GreyWyvern/virtual-keyboard pull request #7
Opened 2024-10-02 19:25 UTC by VitaJane

Here's another change we made. It just adds a button to allow users to move the keyboard around.

2024-10-03 14:47 UTC, GreyWyvern commented
This is great, and something I'd definitely like to add to the script. Thanks!

The main issue with it is that it doesn't account for the page scroll distance. If the viewport hasn't been scrolled at all, it works fine. But if the page has been scrolled down, then the positioning is off.

As well, as a "safety" measure, the movement event listener should also be removed from the document when the keyboard is closed for any reason. So something should be added in `this.VKI_close`.

2024-10-03 18:28 UTC, VitaJane commented
I'll get started adding those

2024-10-03 20:26 UTC, VitaJane commented
Just pushed what I think will fix everything you suggested.

2024-10-04 14:55 UTC, GreyWyvern requested changes
Looks and works nicely now! Just a few more small comments.

2024-10-04 14:55 UTC, GreyWyvern commented on keyboard.js
> +          }
These references should be `self.` to make explicit we are referencing the parent object.

2024-10-04 14:55 UTC, GreyWyvern commented on keyboard.js
> +                keyY = event.pageY + VKI_scrollDist()[1] - cord.top;
There needs to be a fork here based on `self.VKI_target.keyboardPosition == 'fixed'`. If this value is equal to `'fixed'` then scroll distance should be ignored.

Also, these variables should be declared with `let`.

2024-10-04 14:55 UTC, GreyWyvern commented on keyboard.js
> +                moveAt(event.pageX, event.pageY);
Is this function call necessary? If I comment it out it still seems to work, although I might be missing an edge case?

2024-10-04 15:47 UTC, VitaJane commented
Ok, just pushed what should fix those issues, I think. You were right about the one function call being unnecessary. I think I fixed the issue with fixed too, but I'm not sure if I did that right, or understood it all the way.

2024-10-04 16:09 UTC, GreyWyvern approved these changes

2024-10-04 16:12 UTC, GreyWyvern commented
This is looking good, and I can find no further issues with it. If everything's all ship-shape with you, I can merge this.

Thanks!

2024-10-04 16:38 UTC, VitaJane commented
Sounds good to me!

2024-10-04 16:41 UTC, merged